apps/web/urls.py
from django.urls import path

# from .view.auth.login import login
from .views.person.cancel_by_id import cancel_by_id as person_cancel_by_id
from .views.person.dashboard import dashboard as person_dashboard
from .views.person.delete_by_id import detele_by_id as person_detele_by_id
from .views.person.delete_edu_by_id import \
    delete_edu_by_id as person_delete_edu_by_id
from .views.person.delete_work_by_id import \
    delete_work_by_id as person_delete_work_by_id
from .views.person.detail_by_id import detail_by_id as person_detail_by_id
from .views.person.edit_by_id import edit_by_id as person_edit_by_id
from .views.person.registration import registration

app_name = "web"


urlpatterns = [
    # person
    path(route="", view=registration, name="registration"),
    path(route="person/", view=person_dashboard, name="person"),
    path(route="cancel/<str:id>/", view=person_cancel_by_id,
         name="person_cancel_by_id"),
    path(route="edit/<str:id>/", view=person_edit_by_id, name="person_edit_by_id"),
    path(route="detail/<str:id>/", view=person_detail_by_id,
         name="person_detail_by_id"),
    path(route="delete/<str:id>/", view=person_detele_by_id,
         name="person_detele_by_id"),
    path(route="delete-edu/<str:person_id>/<int:id>", view=person_delete_edu_by_id,
         name="person_delete_edu_by_id"),
    path(route="delete-work/<str:person_id>/<int:id>", view=person_delete_work_by_id,
         name="person_delete_work_by_id"),

]

core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    path('admin/', admin.site.urls),
    path(route="", view=include(arg="apps.web.urls")),
]

urlpatterns += static(prefix=MEDIA_URL, document_root=MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Django Data Person</title>

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
    />

    {% block css %}{% endblock css %}
  </head>
  <body>
    {% block apps %}{% endblock apps %}
    <div class="mb-5"></div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>

    <script>
      document.addEventListener("DOMContentLoaded", (event) => {
        const htmlElement = document.documentElement;
        const switchElement = document.getElementById("darkModeSwitch");

        // Set the default theme to dark if no setting is found in local storage
        const currentTheme = localStorage.getItem("bsTheme") || "dark";
        htmlElement.setAttribute("data-bs-theme", currentTheme);
        switchElement.checked = currentTheme === "dark";

        switchElement.addEventListener("change", function () {
          if (this.checked) {
            htmlElement.setAttribute("data-bs-theme", "dark");
            localStorage.setItem("bsTheme", "dark");
          } else {
            htmlElement.setAttribute("data-bs-theme", "light");
            localStorage.setItem("bsTheme", "light");
          }
        });
      });
    </script>

    {% block js %}{% endblock js %}
  </body>
</html>

templates/components/navbar.html
<nav class="navbar fixed-top navbar-expand-lg bg-body-tertiary shadow-sm">
  <div class="container-fluid">
    <!-- button toggle -->
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="offcanvas"
      data-bs-target="#offcanvasExample"
      aria-controls="offcanvasExample"
      aria-label="Toggle navigation"
    >
      <i class="bi bi-grid-3x3-gap-fill fs-2"></i>
    </button>
    <!-- /button toggle -->

    <!-- offcanva -->
    <div
      class="offcanvas offcanvas-start"
      tabindex="-1"
      id="offcanvasExample"
      aria-labelledby="offcanvasExampleLabel"
    >
      <!-- offcanvas header -->
      <div class="offcanvas-header">
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="offcanvas"
          aria-label="Close"
        ></button>
      </div>
      <!-- /offcanvas header -->

      <!-- offcanvas body -->
      <div class="offcanvas-body">
        <div
          class="navbar-nav nav"
          id="navbar-example2"
          data-bs-dismiss="offcanvas"
        >
          <!- - - ->{% for i in nav_core %}<!- - - ->
          <a class="nav-link" href="{{i.link}}">{{i.name}}</a>
          <!- - - ->{% endfor %}<!- - - ->
        </div>
      </div>
      <!-- /offcanvas body -->
    </div>
    <!-- /offcanva -->

    <!-- nav right -->
    <div class="navbar-nav nav list-group list-group-horizontal">
      <!- - - ->{% for i in nav_sosmed %}<!- - - ->
      <a class="nav-link ms-3" href="{{i.link}}" target="_blank">
        <i class="{{i.icon}} h4"></i>
      </a>
      <!- - - ->{% endfor %}<!- - - ->
      <div class="ms-3 d-flex align-items-center">
        <input
          type="checkbox"
          class="btn-check"
          id="darkModeSwitch"
          autocomplete="off"
        />
        <label
          class="btn btn-outline-secondary btn-sm rounded-5"
          for="darkModeSwitch"
        >
          <i class="bi bi-sun-fill"></i> |
          <i class="bi bi-moon-stars-fill"></i>
        </label>
      </div>
    </div>
    <!-- /nav right -->
  </div>
</nav>

templates/pages/person/dashboard.html
<!- -  - ->{%extends "base.html"%}<!- -  - ->

<!- -  - ->{%block css%}<!- -  - ->
<link
  rel="stylesheet"
  href="https://cdn.datatables.net/2.1.7/css/dataTables.bootstrap5.css"
/>

<!-- <link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css"
/> -->
<!- -  - ->{%endblock css%}<!- -  - ->

<!- -  - ->{%block apps%}<!- -  - ->
<!- -  - ->{%include "components/navbar.html"%}<!- -  - ->
<div class="container-fluid" style="padding-top: 70px">
  <div class="shadow-sm p-2 mb-3 bg-body-tertiary rounded">
    <div class="fs-1 text-center">Person</div>
  </div>
  <div class="shadow-sm p-3 mb-3 bg-body-tertiary rounded">
    <table id="person" class="table table-striped" style="width: 100%">
      <thead>
        <tr>
          <th style="min-width: 200px">Name</th>
          <th style="min-width: 250px">Email</th>
          <th class="text-center">Gender</th>
          <th class="text-center">Age</th>
          <th style="min-width: 200px">Created At</th>
          <th style="min-width: 150px" class="text-center">Action</th>
        </tr>
      </thead>
      <tbody>
        <!- -  - ->{% for i in person %}<!- -  - ->
        <tr>
          <td>{{ i.name }}</td>
          <td>{{ i.email }}</td>
          <td class="text-center">
            {% if i.gender == "1" %} Pria {% else %} Wanita {% endif %}
          </td>
          <td class="text-center">{{ i.age }}</td>
          <td>{{ i.created_at|date:"d M Y" }}</td>
          <td class="text-center">
            <a
              href="{% url 'web:person_detail_by_id' i.person_id %}"
              class="btn btn-primary"
            >
              <i class="bi bi-eye-fill me-2"></i>view
            </a>
          </td>
        </tr>
        <!- -  - ->{% endfor %}<!- -  - ->
      </tbody>
    </table>
  </div>
</div>
<!- -  - ->{%endblock apps%}<!- -  - ->

<!- -  - ->{%block js%}<!- -  - ->
<script src="https://code.jquery.com/jquery-3.7.1.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/2.1.7/js/dataTables.js"></script>
<script src="https://cdn.datatables.net/2.1.7/js/dataTables.bootstrap5.js"></script>
<script>
  new DataTable("#person", {
    scrollX: true,
    scrollY: 410,
  });
</script>
<!- -  - ->{%endblock js%}<!- -  - ->

templates/pages/person/form/detail_by_id/bio.html
<fieldset disabled="disabled">
  <div class="row g-3 mb-2">
    <div class="col-lg-12 text-center">
      {% if person.photo %}
      <img
        src="{{ person.photo.url }}"
        class="rounded-5 img-fluid img-thumbnail"
        alt="..."
        style="max-width: 240px; max-height: 240px"
        loading="lazy"
        decoding="async"
      />
      {% elif not person.photo %}
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="240"
        height="240"
        fill="currentColor"
        class="bi bi-person-square"
        viewBox="0 0 16 16"
      >
        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0" />
        <path
          d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zm12 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1v-1c0-1-1-4-6-4s-6 3-6 4v1a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1z"
        />
      </svg>
      {% endif %}
    </div>
    <div class="col-lg-6">
      <div class="row g-3">
        <div class="col-12">
          <div class="mb-1">
            {{field.name.label}} <span class="text-danger">*</span>
          </div>
          {{field.name}}
          <div class="text-danger">{{field.name.errors}}</div>
        </div>
        <div class="col-12">
          <div class="mb-1">
            {{field.email.label}} <span class="text-danger">*</span>
          </div>
          {{field.email}}
          <div class="text-danger">{{field.email.errors}}</div>
        </div>
        <div class="col-12">
          <div class="mb-1">
            {{field.gender.label}} <span class="text-danger">*</span>
          </div>
          <select
            class="form-select"
            aria-label="Default select example"
            name="gender"
          >
            <!- -  - ->{% for i in opt_gender %}<!- -  - ->
            <!- -  - ->{% if field.gender.value == i.0 %}<!- -  - ->
            <option selected value="{{ i.0 }}">{{ i.1 }}</option>
            <!- -  - ->{% else %}<!- -  - ->
            <option value="{{ i.0 }}">{{ i.1 }}</option>
            <!- -  - ->{% endif %}<!- -  - ->
            <!- -  - ->{% endfor %}<!- -  - ->
          </select>
          <div class="text-danger">{{field.gender.errors}}</div>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="row g-3">
        <div class="col-12">
          <div class="mb-1">
            {{field.age.label}} <span class="text-danger">*</span>
          </div>
          {{field.age}}
          <div class="text-danger">{{field.age.errors}}</div>
        </div>
        <div class="col-12">
          <div class="mb-1">
            {{field.phone.label}} <span class="text-danger">*</span>
          </div>
          {{field.phone}}
          <div class="text-danger">{{field.phone.errors}}</div>
        </div>
        <div class="col-12">
          <div class="mb-1">{{field.photo.label}}</div>
          {{field.photo}}
          <div class="text-danger">{{field.photo.errors}}</div>
        </div>
      </div>
    </div>
  </div>

  <div class="mt-3">
    <div class="mb-1">
      {{field.address.label}} <span class="text-danger">*</span>
    </div>
    {{field.address}}
    <div class="text-danger">{{field.address.errors}}</div>
  </div>
</fieldset>

templates/pages/person/form/detail_by_id/btn_control.html
<a
  class="btn btn-warning ms-2"
  href="{% url 'web:person_edit_by_id' person.person_id %}"
  ><i class="bi bi-pencil-square me-2"></i>Edit
</a>
<button
  type="button"
  class="btn btn-danger ms-2"
  data-bs-toggle="modal"
  data-bs-target="#deleteByIdModal"
>
  <i class="bi bi-trash me-2"></i>Delete
</button>

<!-- modal delete_by_id -->
<div
  class="modal fade"
  id="deleteByIdModal"
  tabindex="-1"
  aria-labelledby="deleteByIdModalLabel"
  aria-hidden="true"
  data-bs-backdrop="static"
  data-bs-keyboard="false"
>
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteByIdModalLabel">Warning</h5>
      </div>
      <div class="modal-body">Do you want to delete this Person ?</div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          No
        </button>
        <a
          href="{% url 'web:person_detele_by_id' person.person_id %}"
          class="btn btn-danger"
        >
          Yes
        </a>
      </div>
    </div>
  </div>
</div>
<!-- /modal delete_by_id -->

templates/pages/person/form/detail_by_id/edu.html
<div class="row">
  <div class="col">
    <div class="fs-4">Education<i class="bi bi-book ms-2"></i></div>
  </div>
</div>
<table id="table_edu" class="table table-striped" style="width: 100%">
  <thead>
    <tr>
      <th style="min-width: 250px">Name</th>
      <th style="min-width: 200px" class="text-start">Major</th>
      <th style="min-width: 150px" class="text-center">Category</th>
      <th style="min-width: 100px" class="text-center">Date In</th>
      <th style="min-width: 100px" class="text-center">Date Out</th>
    </tr>
  </thead>
  <tbody>
    <!- -  - ->{% for i in edu %}<!- -  - ->
    <tr>
      <td>{{ i.education_nm }}</td>
      <td>{{ i.major }}</td>
      <td class="text-center">{{ i.category }}</td>
      <td class="text-center">{{ i.date_in|date:"M Y" }}</td>
      <td class="text-center">{{ i.date_out|date:"M Y" }}</td>
    </tr>
    <!- -  - ->{% endfor %}<!- -  - ->
  </tbody>
</table>

templates/pages/person/form/detail_by_id/work.html
<div class="row">
  <div class="col">
    <div class="fs-4">Work Experience<i class="bi bi-gear ms-2"></i></div>
  </div>
</div>
<table id="table_work" class="table table-striped" style="width: 100%">
  <thead>
    <tr>
      <th style="min-width: 250px">Name</th>
      <th style="min-width: 200px" class="text-start">Industry</th>
      <th style="min-width: 150px" class="text-center">Role</th>
      <th style="min-width: 100px" class="text-center">Date In</th>
      <th style="min-width: 100px" class="text-center">Date Out</th>
    </tr>
  </thead>
  <tbody>
    <!- -  - ->{% for i in work %}<!- -  - ->
    <tr>
      <td>{{ i.company_nm }}</td>
      <td>{{ i.industry }}</td>
      <td class="text-center">{{ i.role }}</td>
      <td class="text-center">{{ i.date_in|date:"M Y" }}</td>
      <td class="text-center">{{ i.date_out|date:"M Y" }}</td>
    </tr>
    <!- -  - ->{% endfor %}<!- -  - ->
  </tbody>
</table>

templates/pages/person/form/edit_by_id/bio.html
<div class="row g-3 mb-2">
  <div class="col-lg-12 text-center">
    <!- - {% if page != "registration" and person.photo %} - ->
    <img
      src="{{ person.photo.url }}"
      class="rounded-5 img-fluid img-thumbnail"
      alt="..."
      style="max-width: 240px; max-height: 240px"
      loading="lazy"
      decoding="async"
    />
    <!- - {% elif page != "registration" and not person.photo %} - ->
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="240"
      height="240"
      fill="currentColor"
      class="bi bi-person-square"
      viewBox="0 0 16 16"
    >
      <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0" />
      <path
        d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zm12 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1v-1c0-1-1-4-6-4s-6 3-6 4v1a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1z"
      />
    </svg>
    <!- - {% endif %} - ->
  </div>
  <div class="col-lg-6">
    <div class="row g-3">
      <div class="col-12">
        <div class="mb-1">
          {{field.name.label}} <span class="text-danger">*</span>
        </div>
        {{field.name}}
        <div class="text-danger">{{field.name.errors}}</div>
      </div>
      <div class="col-12">
        <div class="mb-1">
          {{field.email.label}} <span class="text-danger">*</span>
        </div>
        {{field.email}}
        <div class="text-danger">{{field.email.errors}}</div>
      </div>
      <div class="col-12">
        <div class="mb-1">
          {{field.gender.label}} <span class="text-danger">*</span>
        </div>
        <select
          class="form-select"
          aria-label="Default select example"
          name="gender"
        >
          <!- -{% for i in opt_gender %}  - ->
          <!- - {% if field.gender.value == i.0 %} - ->
          <option selected value="{{ i.0 }}">{{ i.1 }}</option>
          <!- - {% else %} - ->
          <option value="{{ i.0 }}">{{ i.1 }}</option>
          <!- - {% endif %} - ->
          <!- - {% endfor %} - ->
        </select>
        <div class="text-danger">{{field.gender.errors}}</div>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="row g-3">
      <div class="col-12">
        <div class="mb-1">
          {{field.age.label}} <span class="text-danger">*</span>
        </div>
        {{field.age}}
        <div class="text-danger">{{field.age.errors}}</div>
      </div>
      <div class="col-12">
        <div class="mb-1">
          {{field.phone.label}} <span class="text-danger">*</span>
        </div>
        {{field.phone}}
        <div class="text-danger">{{field.phone.errors}}</div>
      </div>
      <div class="col-12">
        <div class="mb-1">{{field.photo.label}}</div>
        {{field.photo}}
        <div class="text-danger">{{field.photo.errors}}</div>
      </div>
    </div>
  </div>
</div>

<div class="mt-3">
  <div class="mb-1">
    {{field.address.label}} <span class="text-danger">*</span>
  </div>
  {{field.address}}
  <div class="text-danger">{{field.address.errors}}</div>
</div>

templates/pages/person/form/edit_by_id/btn_control.html
<button type="submit" name="finish" class="btn btn-primary">
  <i class="bi bi-floppy me-2"></i>Save
</button>
<a
  href="{% url 'web:person_cancel_by_id' person.person_id %}"
  class="btn btn-danger ms-2"
>
  <i class="bi bi-x-square me-2"></i>Cancel
</a>

templates/pages/person/form/edit_by_id/edu.html
<div class="row">
  <div class="col">
    <div class="fs-4">Education<i class="bi bi-book ms-2"></i></div>
  </div>
  <div class="col text-end">
    <button
      class="btn btn-secondary text-align-middle"
      type="button"
      data-bs-toggle="modal"
      data-bs-target="#addEduModal"
    >
      <i class="bi bi-plus-square me-2"></i>
      Add
    </button>
  </div>
</div>
<table id="table_edu" class="table table-striped" style="width: 100%">
  <thead>
    <tr>
      <th style="min-width: 250px">Name</th>
      <th style="min-width: 200px" class="text-start">Major</th>
      <th style="min-width: 150px" class="text-center">Category</th>
      <th style="min-width: 100px" class="text-center">Date In</th>
      <th style="min-width: 100px" class="text-center">Date Out</th>
      <th class="text-center">Action</th>
    </tr>
  </thead>
  <tbody>
    <!- - - ->{% for i in edu %}<!- - - ->
    <tr>
      <td class="align-middle">{{ i.education_nm }}</td>
      <td class="align-middle">{{ i.major }}</td>
      <td class="text-center align-middle">{{ i.category }}</td>
      <td class="text-center align-middle">{{ i.date_in|date:"M Y" }}</td>
      <td class="text-center align-middle">{{ i.date_out|date:"M Y" }}</td>
      <td class="text-center align-middle">
        <a
          href="{% url 'web:person_delete_edu_by_id' person.person_id i.id %}"
          class="btn btn-danger"
          ><i class="bi bi-trash"></i
        ></a>
      </td>
    </tr>
    <!- - - ->{% endfor %}<!- - - ->
  </tbody>
</table>

templates/pages/person/form/edit_by_id/modal_add_edu.html
<form method="post">
  {% csrf_token %}
  <div
    class="modal fade"
    id="addEduModal"
    tabindex="-1"
    aria-labelledby="addEduModalLabel"
    aria-hidden="true"
    data-bs-backdrop="static"
    data-bs-keyboard="false"
  >
    <div class="modal-dialog modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <div class="modal-title h5" id="addEduModalLabel">Education</div>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>
        </div>
        <div class="modal-body">
          <div class="row gy-3">
            <div class="col-12">
              <div class="mb-1">
                Name<span class="text-danger ms-1">*</span>
              </div>
              {{ field_edu.education_nm }}
              <div class="text-danger">{{data.education_nm.errors}}</div>
            </div>
            <div class="col-12">
              <div class="mb-1">
                {{ field_edu.major.label }}
                <span class="text-danger ms-1">*</span>
              </div>
              {{ field_edu.major }}
              <div class="text-danger">{{data.major.errors}}</div>
            </div>
            <div class="col-12">
              <div class="mb-1">
                {{ field_edu.category.label }}
                <span class="text-danger ms-1">*</span>
              </div>
              {{ field_edu.category }}
              <div class="text-danger">{{data.category.errors}}</div>
            </div>
            <div class="col-12">
              <div class="mb-1">
                {{ field_edu.date_in.label }}
                <span class="text-danger ms-1">*</span>
              </div>
              {{ field_edu.date_in }}
              <div class="text-danger">{{data.date_in.errors}}</div>
            </div>
            <div class="col-12">
              <div class="mb-1">
                {{ field_edu.date_out.label }}
                <span class="text-danger ms-1">*</span>
              </div>
              {{ field_edu.date_out }}
              <div class="text-danger">{{data.date_out.errors}}</div>
            </div>
            <div class="mb-1"></div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="submit" name="add_edu" class="btn btn-secondary">
            <i class="bi bi-plus-square me-2"></i>Add
          </button>
        </div>
      </div>
    </div>
  </div>
</form>

templates/pages/person/form/edit_by_id/modal_add_work.html
<form method="post">
  {% csrf_token %}
  <div
    class="modal fade"
    id="addWorkModal"
    tabindex="-1"
    aria-labelledby="addWorkModalLabel"
    aria-hidden="true"
    data-bs-backdrop="static"
    data-bs-keyboard="false"
  >
    <div class="modal-dialog modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <div class="modal-title h5" id="addWorkModalLabel">
            Work Experience
          </div>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>
        </div>
        <div class="modal-body">
          <div class="row gy-3">
            <div class="col-12">
              <div class="mb-1">
                Name<span class="text-danger ms-1">*</span>
              </div>
              {{ field_work.company_nm }}
              <div class="text-danger">{{data.company_nm.errors}}</div>
            </div>
            <div class="col-12">
              <div class="mb-1">
                {{ field_work.industry.label }}
                <span class="text-danger ms-1">*</span>
              </div>
              {{ field_work.industry }}
              <div class="text-danger">{{data.industry.errors}}</div>
            </div>
            <div class="col-12">
              <div class="mb-1">
                {{ field_work.role.label }}
                <span class="text-danger ms-1">*</span>
              </div>
              {{ field_work.role }}
              <div class="text-danger">{{data.role.errors}}</div>
            </div>
            <div class="col-12">
              <div class="mb-1">
                {{ field_work.date_in.label }}
                <span class="text-danger ms-1">*</span>
              </div>
              {{ field_work.date_in }}
              <div class="text-danger">{{data.date_in.errors}}</div>
            </div>
            <div class="col-12">
              <div class="mb-1">
                {{ field_work.date_out.label }}
                <span class="text-danger ms-1">*</span>
              </div>
              {{ field_work.date_out }}
              <div class="text-danger">{{data.date_out.errors}}</div>
            </div>
            <div class="mb-1"></div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="submit" name="add_work" class="btn btn-secondary">
            <i class="bi bi-plus-square me-2"></i>Add
          </button>
        </div>
      </div>
    </div>
  </div>
</form>

templates/pages/person/form/edit_by_id/work.html
<div class="row">
  <div class="col">
    <div class="fs-4">Work Experience<i class="bi bi-gear ms-2"></i></div>
  </div>
  <div class="col text-end">
    <button
      class="btn btn-secondary text-align-middle"
      type="button"
      data-bs-toggle="modal"
      data-bs-target="#addWorkModal"
    >
      <i class="bi bi-plus-square me-2"></i>
      Add
    </button>
  </div>
</div>
<table id="table_work" class="table table-striped" style="width: 100%">
  <thead>
    <tr>
      <th style="min-width: 250px">Name</th>
      <th style="min-width: 200px" class="text-start">Indrustry</th>
      <th style="min-width: 150px" class="text-center">Role</th>
      <th style="min-width: 100px" class="text-center">Date In</th>
      <th style="min-width: 100px" class="text-center">Date Out</th>
      <th class="text-center">Action</th>
    </tr>
  </thead>
  <tbody>
    <!- - - ->{% for i in work %}<!- - - ->
    <tr>
      <td class="align-middle">{{ i.company_nm }}</td>
      <td class="align-middle">{{ i.industry }}</td>
      <td class="text-center align-middle">{{ i.role }}</td>
      <td class="text-center align-middle">{{ i.date_in|date:"M Y" }}</td>
      <td class="text-center align-middle">{{ i.date_out|date:"M Y" }}</td>
      <td class="text-center align-middle">
        <a
          href="{% url 'web:person_delete_work_by_id' person.person_id i.id %}"
          class="btn btn-danger"
          ><i class="bi bi-trash"></i
        ></a>
      </td>
    </tr>
    <!- - - ->{% endfor %}<!- - - ->
  </tbody>
</table>